// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9Ddq0p3xYHRQGw8E36YDiSGyEVMGl4iU',
    appId: '1:516816025242:web:e2a9e21ef91837cac31123',
    messagingSenderId: '516816025242',
    projectId: 'weather-471fe',
    authDomain: 'weather-471fe.firebaseapp.com',
    storageBucket: 'weather-471fe.firebasestorage.app',
    measurementId: 'G-RQ4SDTKCL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhRX4ulqLn0nE9QayUSasHEYdPga11gRo',
    appId: '1:516816025242:android:46c56cf5e7aa9e0cc31123',
    messagingSenderId: '516816025242',
    projectId: 'weather-471fe',
    storageBucket: 'weather-471fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3N_Bz0JpKQNY_da4qbPKEDXkoCjJmmxI',
    appId: '1:516816025242:ios:67bfd2a63adfc5a7c31123',
    messagingSenderId: '516816025242',
    projectId: 'weather-471fe',
    storageBucket: 'weather-471fe.firebasestorage.app',
    iosBundleId: 'com.example.health',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3N_Bz0JpKQNY_da4qbPKEDXkoCjJmmxI',
    appId: '1:516816025242:ios:67bfd2a63adfc5a7c31123',
    messagingSenderId: '516816025242',
    projectId: 'weather-471fe',
    storageBucket: 'weather-471fe.firebasestorage.app',
    iosBundleId: 'com.example.health',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9Ddq0p3xYHRQGw8E36YDiSGyEVMGl4iU',
    appId: '1:516816025242:web:e3f1344ffd6d01f1c31123',
    messagingSenderId: '516816025242',
    projectId: 'weather-471fe',
    authDomain: 'weather-471fe.firebaseapp.com',
    storageBucket: 'weather-471fe.firebasestorage.app',
    measurementId: 'G-GHFB50FL7B',
  );

}